mindmap
  root((Terminal Commands))
    Navigation
      pwd - Print Working Dir
      ls - List Files
      cd - Change Directory
      mkdir - Make Directory
      rmdir - Remove Directory
    File_Operations
      touch - Create Empty File
      cp - Copy File
      mv - Move/Rename File
      rm - Remove File (careful!)
      cat - View File Content
    C_Development
      gcc main.c -o prog - Compile
      ./prog - Run the program
      gcc -Wall -Werror - Pedantic mode
      valgrind ./prog - Check memory
    Tips
      Tab - Auto-complete
      Up/Down - Command history
      Ctrl+C - Stop running program
      Ctrl+D - Exit terminal
      man command - Read manual
