mindmap
  root((Foundations of<br/>Programming))
    Phase1_Foundation
      Ch00_Why_Programming
      Ch01_How_Computers_Work
      Ch02_Setup_Tools
    Phase2_C_Language
      Ch03_Variables_Types
      Ch04_Operators
      Ch05_Control_Flow
      Ch06_Loops
      Ch07_Functions
      Ch08_Arrays_Strings
      Ch09_Pointers
      Ch10_Memory
      Ch11_Structures
      Ch12_File_IO
    Phase3_Data_Structures
      Ch13_DS_Fundamentals
      Ch14_Algorithms
    Phase4_Big_Picture
      Ch15_Languages
    Phase5_Capstone
      Ch16_Final_Project
